### ISSUE TITLE
adm-zip errors when trying to unzip resource_hacker.zip

### ISSUE THREAD

**Issue by gcatto** [si458/changeexe#1]
I have used changexe for a while (thanks for making it) and it has always downloaded and unzipped Resource Hacker fine, both for development and as part of CI pipelines and such.

However, earlier this week, it started giving errors. For example, on Windows:
```
npm ERR! code 1
npm ERR! path C:\Users\foo\Appdata\Roaming\nvm\v18.15.0\node_modules\changeexe
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node dlResHack
npm ERR! The license of ResourceHacker.exe forbids distribution with this NPM package, so it will be downloaded at this time.
npm ERR! Downloading resource_hacker.zip ...
npm ERR! Download Completed
npm ERR! Extracting resource_hacker.zip ...
npm ERR! C:\Users\foo\Appdata\Roaming\nvm\v18.15.0\node_modules\changeexe\node_modules\adm-zip\zipFile.js:101
npm ERR!         if (!~endOffset) throw new Error(Utils.Errors.INVALID_FORMAT);
npm ERR!                          ^
npm ERR!
npm ERR! Error: Invalid or unsupported zip format. No END header found
npm ERR!     at readMainHeader (C:\Users\foo\Appdata\Roaming\nvm\v18.15.0\node_modules\changeexe\node_modules\adm-zip\zipFile.js:101:32)
npm ERR!     at new module.exports (C:\Users\foo\Appdata\Roaming\nvm\v18.15.0\node_modules\changeexe\node_modules\adm-zip\zipFile.js:19:9)
npm ERR!     at new module.exports (C:\Users\foo\Appdata\Roaming\nvm\v18.15.0\node_modules\changeexe\node_modules\adm-zip\adm-zip.js:62:18)
npm ERR!     at WriteStream.<anonymous> (C:\Users\foo\Appdata\Roaming\nvm\v18.15.0\node_modules\changeexe\dlResHack.js:19:21)
npm ERR!     at WriteStream.emit (node:events:525:35)
npm ERR!     at finish (node:internal/streams/writable:748:10)
npm ERR!     at finishMaybe (node:internal/streams/writable:733:9)
npm ERR!     at afterWrite (node:internal/streams/writable:507:3)
npm ERR!     at onwrite (node:internal/streams/writable:480:7)
npm ERR!     at node:internal/fs/streams:410:5
npm ERR!
npm ERR! Node.js v18.15.0
```

I get similar errors in my Linux-based CI pipelines. I noticed that Resource Hacker recently released a new version (5.2.3) and the date roughly corresponds to when things started breaking. Strangely I can still download the resource_hacker.zip manually and unzip it using OS unzip tools/commands fine.

**Comment by si458** [comment]
I totally forgot I made this! I will have a look tomorrow when I'm stationary for you, I might just need to update something

**Comment by gcatto** [comment]
Hah! Thanks kindly!

**Comment by howraf11** [comment]
Looks like dlResHack.js just needs to be changed from http to https.

**Comment by si458** [comment]
thanks @howraf11 for the hint!
@gcatto give v1.0.3 a go!

**Comment by howraf11** [comment]
I work with @gcatto (who is out of office for a couple of days) and can confirm that 1.0.3 fixes the issue. Thanks so much for turning this around quickly. Happy we got to remind you of this utility, it works very nicely for us, so we appreciate it.

**Comment by si458** [comment]
@howraf11 great! Glad it works! And glad u have a use case for it!
